# Analyze the log files generated by cProfile
# Jie (Laurie) Zhang
# 04/01/15
# e.g. python ReadLog.py logfile_name
import sys
import pstats

p = pstats.Stats(sys.argv[1])
p.strip_dirs().sort_stats('cumulative').print_stats(10)